/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;


import Conrtoller.CrearController;
import Models.DatosExamen;

/**
 *
 * @author Kenneth Granados
 */
public final class CrearExamen extends javax.swing.JInternalFrame {
 CrearController cc;
    /**
     * Creates new form EditarExamen
     */
    public CrearExamen() {
        initComponents();
       setupController();
    }
    
public void setupController(){
    cc = new CrearController(this);
    cleanButton.addActionListener(cc);
    saveButton.addActionListener(cc);
    editButton.addActionListener(cc);
}

public DatosExamen getData(){ //guardar de datos
  DatosExamen de = new DatosExamen();
    de.setPreg1(preg1TextField.getText());
    de.setPreg3(preg3TextField.getText());
    de.setPreg4(preg4TextField.getText());
    de.setPreg5(preg5TextField.getText());
    de.setPreg2(preg2TextField.getText());
    de.setResp1p1(Resp1p1TextField.getText());
    de.setResp2p1(Resp2p1TextField.getText());
    de.setResp3p1(Resp3p1TextField.getText());
    de.setResp4p1(Resp4p1TextField.getText());
    de.setResp1p2(Resp1p2TextField.getText());
    de.setResp2p2(Resp2p2TextField.getText());
    de.setResp3p2(Resp3p2TextField.getText());
    de.setResp4p2(Resp4p2TextField.getText());
    de.setResp1p3(Resp1p3TextField.getText());
    de.setResp2p3(Resp2p3TextField.getText());
    de.setResp3p3(Resp3p3TextField.getText());
    de.setResp4p3(Resp4p3TextField.getText());
    de.setResp1p4(Resp1p4TextField.getText());
    de.setResp2p4(Resp2p4TextField.getText());
    de.setResp3p4(Resp3p4TextField.getText());
    de.setResp4p4(Resp4p4TextField.getText());
    de.setResp1p5(Resp1p5TextField.getText());
    de.setResp2p5(Resp2p5TextField.getText());
    de.setResp3p5(Resp3p5TextField.getText());
    de.setResp4p5(Resp4p5TextField.getText());
    
    return de;
}
  
public void setData(DatosExamen de){ //carga de datos
    preg1TextField.setText(de.getPreg1());
    preg3TextField.setText(de.getPreg3());
    preg4TextField.setText(de.getPreg4());
    preg5TextField.setText(de.getPreg5());
    preg2TextField.setText(de.getPreg2());
    Resp1p1TextField.setText(de.getResp1p1());
    Resp2p1TextField.setText(de.getResp2p1());
    Resp3p1TextField.setText(de.getResp3p1());
    Resp4p1TextField.setText(de.getResp4p1());
    Resp1p2TextField.setText(de.getResp1p2());
    Resp2p2TextField.setText(de.getResp2p2());
    Resp3p2TextField.setText(de.getResp3p2());
    Resp4p2TextField.setText(de.getResp4p2());
    Resp1p3TextField.setText(de.getResp1p3());
    Resp2p3TextField.setText(de.getResp2p3());
    Resp3p3TextField.setText(de.getResp3p3());
    Resp4p3TextField.setText(de.getResp4p3());
    Resp1p4TextField.setText(de.getResp1p4());
    Resp2p4TextField.setText(de.getResp2p4());
    Resp3p4TextField.setText(de.getResp3p4());
    Resp4p4TextField.setText(de.getResp4p4());
    Resp1p5TextField.setText(de.getResp1p5());
    Resp2p5TextField.setText(de.getResp2p5());
    Resp3p5TextField.setText(de.getResp3p5());
    Resp4p5TextField.setText(de.getResp4p5());
    
}

 public void clean() { //limpiado de datos
    preg1TextField.setText("");
    preg3TextField.setText("");
    preg4TextField.setText("");
    preg5TextField.setText("");
    preg2TextField.setText("");
    Resp1p1TextField.setText("");
    Resp2p1TextField.setText("");
    Resp3p1TextField.setText("");
    Resp4p1TextField.setText("");
    Resp1p2TextField.setText("");
    Resp2p2TextField.setText("");
    Resp3p2TextField.setText("");
    Resp4p2TextField.setText("");
    Resp1p3TextField.setText("");
    Resp2p3TextField.setText("");
    Resp3p3TextField.setText("");;
    Resp4p3TextField.setText("");;
    Resp2p4TextField.setText("");;
    Resp3p4TextField.setText("");;
    Resp4p4TextField.setText("");;
    Resp1p5TextField.setText("");;
    Resp2p5TextField.setText("");;
    Resp3p5TextField.setText("");;
    Resp4p5TextField.setText("");;
    Resp1p4TextField.setText("");;

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        preg1TextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Resp1p1TextField = new javax.swing.JTextField();
        Resp2p1TextField = new javax.swing.JTextField();
        Resp3p1TextField = new javax.swing.JTextField();
        Resp4p1TextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Resp1p5TextField = new javax.swing.JTextField();
        Resp2p5TextField = new javax.swing.JTextField();
        Resp4p5TextField = new javax.swing.JTextField();
        Resp3p5TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        preg2TextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Resp1p2TextField = new javax.swing.JTextField();
        Resp2p2TextField = new javax.swing.JTextField();
        Resp4p2TextField = new javax.swing.JTextField();
        Resp3p2TextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        preg3TextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Resp1p3TextField = new javax.swing.JTextField();
        Resp2p3TextField = new javax.swing.JTextField();
        Resp4p3TextField = new javax.swing.JTextField();
        Resp3p3TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        preg4TextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        preg5TextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Resp2p4TextField = new javax.swing.JTextField();
        Resp1p4TextField = new javax.swing.JTextField();
        Resp3p4TextField = new javax.swing.JTextField();
        Resp4p4TextField = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        cleanButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel1.setText("Pregunta 1");

        preg1TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        preg1TextField.setText("Pregunta 1?");

        jLabel7.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel7.setText("Posibles respuesta pregunta 1");

        Resp1p1TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp1p1TextField.setText("Resp1");

        Resp2p1TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp2p1TextField.setText("Resp2");

        Resp3p1TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp3p1TextField.setText("Resp3");

        Resp4p1TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp4p1TextField.setText("Resp4");

        jLabel11.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel11.setText("Posibles respuesta pregunta 5");

        Resp1p5TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp1p5TextField.setText("Resp1");

        Resp2p5TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp2p5TextField.setText("Resp2");

        Resp4p5TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp4p5TextField.setText("Resp4");

        Resp3p5TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp3p5TextField.setText("Resp3");

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel2.setText("Pregunta 2");

        preg2TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        preg2TextField.setText("Pregunta 2?");

        jLabel8.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel8.setText("Posibles respuesta pregunta 2");

        Resp1p2TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp1p2TextField.setText("Resp1");

        Resp2p2TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp2p2TextField.setText("Resp2");

        Resp4p2TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp4p2TextField.setText("Resp4");

        Resp3p2TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp3p2TextField.setText("Resp3");

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel3.setText("Pregunta 3");

        preg3TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        preg3TextField.setText("Pregunta 3?");

        jLabel9.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel9.setText("Posibles respuesta pregunta 3");

        Resp1p3TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp1p3TextField.setText("Resp1");

        Resp2p3TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp2p3TextField.setText("Resp2");

        Resp4p3TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp4p3TextField.setText("Resp4");

        Resp3p3TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp3p3TextField.setText("Resp3");

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel5.setText("Pregunta 4");

        preg4TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        preg4TextField.setText("Pregunta 5?");

        jLabel6.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel6.setText("Pregunta 5");

        preg5TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        preg5TextField.setText("Pregunta 5?");

        jLabel10.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel10.setText("Posibles respuesta pregunta 4");

        Resp2p4TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp2p4TextField.setText("Resp2");

        Resp1p4TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp1p4TextField.setText("Resp1");

        Resp3p4TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp3p4TextField.setText("Resp3");

        Resp4p4TextField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Resp4p4TextField.setText("Resp4");

        editButton.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        editButton.setText("Editar");

        cleanButton.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        cleanButton.setText("Limpiar");

        saveButton.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        saveButton.setText("Guardar");
        saveButton.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(preg1TextField)
                    .addComponent(preg3TextField)
                    .addComponent(preg2TextField)
                    .addComponent(preg4TextField)
                    .addComponent(preg5TextField)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(95, 95, 95)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(saveButton)
                                .addGap(28, 28, 28)
                                .addComponent(cleanButton)
                                .addGap(71, 71, 71))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Resp2p1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Resp1p1TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Resp3p1TextField)
                                            .addComponent(Resp4p1TextField)))
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Resp1p5TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                            .addComponent(Resp2p5TextField))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Resp4p5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Resp3p5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11))))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Resp1p2TextField)
                                    .addComponent(Resp2p2TextField))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Resp4p2TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(Resp3p2TextField))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Resp1p3TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(Resp2p3TextField))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Resp3p3TextField)
                                    .addComponent(Resp4p3TextField)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Resp1p4TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(Resp2p4TextField))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Resp3p4TextField)
                                    .addComponent(Resp4p4TextField))))
                        .addGap(0, 356, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Resp1p5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Resp3p5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Resp2p5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Resp4p5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(preg1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Resp1p1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Resp3p1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Resp2p1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Resp4p1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Resp1p2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Resp3p2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Resp2p2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Resp4p2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Resp1p3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Resp3p3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Resp2p3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Resp4p3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Resp3p4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Resp1p4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Resp2p4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Resp4p4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton)
                            .addComponent(cleanButton)
                            .addComponent(editButton)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(preg2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preg3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preg4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(preg5TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Resp1p1TextField;
    private javax.swing.JTextField Resp1p2TextField;
    private javax.swing.JTextField Resp1p3TextField;
    private javax.swing.JTextField Resp1p4TextField;
    private javax.swing.JTextField Resp1p5TextField;
    private javax.swing.JTextField Resp2p1TextField;
    private javax.swing.JTextField Resp2p2TextField;
    private javax.swing.JTextField Resp2p3TextField;
    private javax.swing.JTextField Resp2p4TextField;
    private javax.swing.JTextField Resp2p5TextField;
    private javax.swing.JTextField Resp3p1TextField;
    private javax.swing.JTextField Resp3p2TextField;
    private javax.swing.JTextField Resp3p3TextField;
    private javax.swing.JTextField Resp3p4TextField;
    private javax.swing.JTextField Resp3p5TextField;
    private javax.swing.JTextField Resp4p1TextField;
    private javax.swing.JTextField Resp4p2TextField;
    private javax.swing.JTextField Resp4p3TextField;
    private javax.swing.JTextField Resp4p4TextField;
    private javax.swing.JTextField Resp4p5TextField;
    private javax.swing.JButton cleanButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField preg1TextField;
    private javax.swing.JTextField preg2TextField;
    private javax.swing.JTextField preg3TextField;
    private javax.swing.JTextField preg4TextField;
    private javax.swing.JTextField preg5TextField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
