/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;


import Conrtoller.MainController;
import javax.swing.JInternalFrame;

/**
 *
 * @author Kenneth Granados
 */
public class Principal extends javax.swing.JFrame {
    MainController mc;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setupController();
    }

     public void setupController(){
         mc = new MainController(this);
         cargarMenuItem.addActionListener(mc);
         crearMenuItem.addActionListener(mc);
         FuncionMenuItem.addActionListener(mc);
     }
       public void showChild(JInternalFrame frame, boolean maximmizeframe){
       setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR)); 
      desktop.add(frame);
      frame.setVisible(true);
         if (maximmizeframe) 
             desktop.getDesktopManager().maximizeFrame(frame);
      setCursor(java.awt.Cursor.getDefaultCursor());
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cargarMenuItem = new javax.swing.JMenuItem();
        FuncionMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        crearMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");

        desktop.setForeground(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 237, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );

        jMenu1.setText("Resolver");
        jMenu1.setToolTipText("");
        jMenu1.setActionCommand("");

        cargarMenuItem.setText("Cargar");
        jMenu1.add(cargarMenuItem);

        FuncionMenuItem.setText("Funcion");
        FuncionMenuItem.setToolTipText("");
        jMenu1.add(FuncionMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        crearMenuItem.setText("Crear");
        jMenu2.add(crearMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem FuncionMenuItem;
    private javax.swing.JMenuItem cargarMenuItem;
    private javax.swing.JMenuItem crearMenuItem;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
